### ISSUE TITLE
Update Required

### ISSUE THREAD

**Issue by sam4922** [cabbagegod/going-medieval-devconsole-mod#1]
Hey, so I came from a YouTube video demonstrating your mod. Since this game is so good for making cool functioning castles it comes in handy to just use "sandbox". Since then the developers have updated the game and I can no longer is this mod. I can't reach you on discord because the username is invalid, but me and a lot of other gamers are wanting this mod to be updated.

Thanks

**Comment by cabbagegod** [comment]
Ahh, I see. I think Discord is case sensitive. Thanks for reaching out
though, I honestly had no idea Github included this functionality. I'm
realizing there was a mixup and the mod actually doesn't work for the
latest version, that was my mistake. I can release a modified patch, I've
developed a better version of this mod for the mod loader I am developing
anyway. But I'll still release a standalone version to enable this tool.

**Comment by cabbagegod** [comment]
New update released, hope this helps!
https://github.com/cabbagegod/going-medieval-devconsole-mod/releases

**Comment by sam4922** [comment]
Thanks
