### ISSUE TITLE
Update - Issue with Detail.

### ISSUE THREAD

**Issue by KnightVicrul** [cabbagegod/going-medieval-devconsole-mod#2]
Hello! I'm not able to reach you on discord. But let me write something I sent to a youtuber, this is just something with insight. So don't worry if it sounds weird, I wrote it in a YouTube comments. 

"Hey, I just want to say thankyou for showing us this. But regarding the Mod, as of June 7th, the main game (Going Medieval) was updated to "0.5.28.6", and on the mod page, the Modder states "Verified to still work on v0.5.28.6" but upon loading the game after either clicking any of the game modes (I tried all 3) I and others are shown the game's menu background. I went through the steps exactly around 3 times. Just wondering if you had any insight, if not I'll contact the Modder via discord."

**Comment by cabbagegod** [comment]
I just sent this message to another user who reached out on gitbub.

"Ahh, I see. I think Discord is case sensitive. Thanks for reaching out
though, I honestly had no idea Github included this functionality. I'm
realizing there was a mixup and the mod actually doesn't work for the
latest version, that was my mistake. I can release a modified patch, I've
developed a better version of this mod for the mod loader I am developing
anyway. But I'll still release a standalone version to enable this tool. "

Thanks for reaching out and letting me know, an honest mistake on my end!

**Comment by cabbagegod** [comment]
New update released, hope this helps!
https://github.com/cabbagegod/going-medieval-devconsole-mod/releases

>
